title: "EcoSamana Adventures"
description: "Family-friendly eco tours & pirate treasure hunts in Santa Bárbara de Samaná."
baseurl: ""
url: "https://eco-samana.com"

# Optional: keep or remove minima if unused
theme: minima

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

email: info@eco-samana.com


collections:
  info:
    output: true
    permalink: /info/:name/
